<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
	public function myFind2Random($user, $gender)
	{	

		// First we get all Images ids not uploaded by the user (normally the logged user)
		$queryBuilder = $this->_em->createQueryBuilder()
		->select('i.id')
		->from($this->_entityName, 'i')
		->where('i.ownerId <> :userId')
		->andWhere('i.gender = \''.$gender.'\'')
		->setParameter('userId', $user)
		// ->setParameter('gender', $gender)
		;
		$query = $queryBuilder->getQuery();

    	$listIds = $query->getResult();
    	dump($query);
    	dump(count($listIds));
    	if (count($listIds) < 2) {
    		return false;
    	}
    	
    	// Then we ask two random id from theses results
        $randomKeys = array_rand($listIds, 2);
        $firstId = $listIds[$randomKeys[0]]['id'];
        $secondId = $listIds[$randomKeys[1]]['id']; 

        // Next, we ask the data for theses 2 ids
		$queryBuilder = $this->_em->createQueryBuilder()
		->select('i')
		->from($this->_entityName, 'i')
		->where('i.id in (:firstId, :secondId)')
		->setParameter('firstId', $firstId)
		->setParameter('secondId', $secondId)
		;
		$query = $queryBuilder->getQuery();
    	$results = $query->getResult();

    	// Finally we return the data
    	return $results;
	}

}
