user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

apropos:
    path:     /a_propos
    defaults: { _controller: AppBundle:Default:apropos }   

mentions:
    path:     /mentions
    defaults: { _controller: AppBundle:Default:mentions }    