image_index:
    path:     /
    defaults: { _controller: "AppBundle:Image:index" }
    methods:  GET

image_two_random:
    path:     /vote
    defaults: { _controller: "AppBundle:Image:twoRandom" }
    methods:  GET

vote_submit:
    path:     /vote/submit
    defaults: { _controller: "AppBundle:Image:vote" }
    methods:  POST

image_index_mine:
    path:     /my
    defaults: { _controller: "AppBundle:Image:indexMine" }
    methods:  GET

image_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Image:show" }
    methods:  GET

image_new:
    path:     /new
    defaults: { _controller: "AppBundle:Image:new" }
    methods:  [GET, POST]

# image_edit:
#     path:     /{id}/edit
#     defaults: { _controller: "AppBundle:Image:edit" }
#     methods:  [GET, POST]

image_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Image:delete" }
    methods:  DELETE
